# Generated by Django 5.1.1 on 2025-12-21 18:33

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import encrypted_model_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('viewer', 'Viewer')], default='viewer', max_length=10)),
                ('mfa_secret', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True)),
                ('last_scan_at', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='FirmProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('phone', models.CharField(help_text='e.g +18881234567', max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\+?\\d{7,15}$', 'Enter a valid phone number.')])),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('address', encrypted_model_fields.fields.EncryptedTextField(blank=True)),
                ('timezone', models.CharField(default='UTC', max_length=100)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('date_format', models.CharField(default='%d/%m/%Y', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('_preferences', encrypted_model_fields.fields.EncryptedTextField(blank=True, default='{}')),
                ('subscription_tier', models.CharField(choices=[('trial', 'Trial'), ('basic', 'Basic'), ('pro', 'Professional'), ('enterprise', 'Enterprise')], default='trial', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('selected_frameworks', models.JSONField(blank=True, default=list)),
                ('audit_rigor', models.CharField(choices=[('simple', 'Simple'), ('detailed', 'Detailed')], default='simple', max_length=20)),
                ('retention_days', models.IntegerField(default=365, help_text='Number of days to keep audit logs')),
                ('data_region', models.CharField(default='us', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='firmprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='useraccount',
            name='firm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='users.firmprofile'),
        ),
    ]
