# Generated by Django 5.1.1 on 2025-12-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegulatoryStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='firmprofile',
            name='additional_standards',
            field=models.ManyToManyField(blank=True, related_name='specific_firms', to='users.regulatorystandard'),
        ),
        migrations.CreateModel(
            name='TierStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('trial', 'Trial'), ('basic', 'Basic'), ('pro', 'Professional'), ('enterprise', 'Enterprise')], max_length=20, unique=True)),
                ('standards', models.ManyToManyField(blank=True, to='users.regulatorystandard')),
            ],
        ),
    ]
