# Generated by Django 5.1.1 on 2025-11-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='last_scan_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='firmprofile',
            index=models.Index(fields=['domain'], name='users_firmp_domain_50a6cf_idx'),
        ),
        migrations.AddIndex(
            model_name='firmprofile',
            index=models.Index(fields=['email'], name='users_firmp_email_601b3e_idx'),
        ),
    ]
