# Generated by Django 5.1.1 on 2025-12-21 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmprofile',
            name='active_standard',
            field=models.CharField(default='GDPR', max_length=100),
        ),
        migrations.AddField(
            model_name='firmprofile',
            name='scan_mode',
            field=models.CharField(choices=[('simple', 'Simple'), ('detailed', 'Detailed')], default='simple', max_length=10),
        ),
    ]
