# Generated by Django 5.1.1 on 2025-11-05 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_firmprofile_updated_at_useraccount_last_scan_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='firm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='users.firmprofile'),
        ),
    ]
