# Generated by Django 5.1.1 on 2025-12-27 19:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_regulatorystandard_firmprofile_additional_standards_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='regulatorystandard',
            name='one_liner',
            field=models.CharField(default=django.utils.timezone.now, help_text='Brief description', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regulatorystandard',
            name='scope_tag',
            field=models.CharField(default=django.utils.timezone.now, help_text='e.g., Global, Privacy, Federal', max_length=50),
            preserve_default=False,
        ),
    ]
