# Generated by Django 5.1.1 on 2025-11-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_firmprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmprofile',
            name='phone',
            field=models.CharField(blank=True, help_text='Primary contact phone number', max_length=20, null=True, unique=True),
        ),
    ]
