# Generated by Django 5.1.1 on 2025-11-15 10:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_firmprofile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmprofile',
            name='phone',
            field=models.CharField(help_text='e.g +18881234567', max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\+?\\d{7,15}$', 'Enter a valid phone number.')]),
        ),
    ]
