# Generated by Django 5.1.1 on 2025-11-29 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_firmprofile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmprofile',
            name='subscription_tier',
            field=models.CharField(choices=[('free', 'Free'), ('pro', 'Professional'), ('enterprise', 'Enterprise')], default='free', max_length=20),
        ),
    ]
