# Generated by Django 5.1.1 on 2025-12-16 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_useraccount_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmprofile',
            name='subscription_tier',
            field=models.CharField(choices=[('trial', 'Tiral'), ('basic', 'Basic'), ('pro', 'Professional'), ('enterprise', 'Enterprise')], default='free', max_length=20),
        ),
    ]
