# Generated by Django 5.1.1 on 2025-12-16 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_firmprofile_subscription_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='pending_subscription_tier',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='firmprofile',
            name='subscription_tier',
            field=models.CharField(choices=[('trial', 'Trial'), ('basic', 'Basic'), ('pro', 'Professional'), ('enterprise', 'Enterprise')], default='free', max_length=20),
        ),
    ]
