# Generated by Django 5.1.1 on 2025-12-16 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_useraccount_pending_subscription_tier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='pending_subscription_tier',
        ),
        migrations.AlterField(
            model_name='firmprofile',
            name='subscription_tier',
            field=models.CharField(choices=[('trial', 'Trial'), ('basic', 'Basic'), ('pro', 'Professional'), ('enterprise', 'Enterprise')], default='trial', max_length=20),
        ),
    ]
