# Generated by Django 5.1.1 on 2025-12-21 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_useraccount_pending_subscription_tier_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='firmprofile',
            name='users_firmp_domain_50a6cf_idx',
        ),
        migrations.RemoveIndex(
            model_name='firmprofile',
            name='users_firmp_email_601b3e_idx',
        ),
        migrations.AddField(
            model_name='firmprofile',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='firmprofile',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='firmprofile',
            name='date_format',
            field=models.CharField(default='%d/%m/%Y', max_length=20),
        ),
        migrations.AddField(
            model_name='firmprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='firmprofile',
            name='timezone',
            field=models.CharField(default='UTC', max_length=100),
        ),
    ]
