# Generated by Django 5.1.1 on 2025-12-21 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_firmprofile_users_firmp_domain_50a6cf_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmprofile',
            name='audit_rigor',
            field=models.CharField(choices=[('simple', 'Simple Checklist'), ('detailed', 'Detailed Audit (Evidence Required)')], default='simple', max_length=20),
        ),
        migrations.AddField(
            model_name='firmprofile',
            name='retention_days',
            field=models.IntegerField(default=365, help_text='Number of days to keep audit logs'),
        ),
        migrations.AddField(
            model_name='firmprofile',
            name='selected_frameworks',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
