# Generated by Django 5.1.1 on 2025-12-21 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_firmprofile_audit_rigor_firmprofile_retention_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmprofile',
            name='data_region',
            field=models.CharField(default='us', max_length=10),
        ),
        migrations.AlterField(
            model_name='firmprofile',
            name='audit_rigor',
            field=models.CharField(choices=[('simple', 'Simple'), ('detailed', 'Detailed')], default='simple', max_length=20),
        ),
    ]
