# reports/migrations/0001_initial.py
# Generated by Django 5.1.1 on 2025-12-22 13:50

import django.db.models.deletion
import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifiedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(max_length=16, unique=True)),
                ('domain', models.CharField(max_length=255)),
                ('audit_date', models.DateField()),
                ('generated_at', models.DateTimeField()),
                ('compliance_grade', models.CharField(max_length=4)),
                ('risk_score', models.IntegerField()),
                ('issues_found', models.IntegerField()),
                ('frameworks', models.JSONField()),
                ('pdf_file', models.FileField(upload_to='reports/pdfs/')),
                ('pdf_sha256', models.CharField(max_length=64)),
                ('scanner_signature', models.CharField(default='ComplyLaw AI Scanner', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComplianceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('_findings', encrypted_model_fields.fields.EncryptedTextField(default='[]')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='reports/pdfs/')),
                ('scan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_report', to='scanner.scanresult')),
            ],
            options={
                'verbose_name': 'Compliance Report',
                'verbose_name_plural': 'Compliance Reports',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(max_length=16, unique=True)),
                ('domain', models.CharField(max_length=255)),
                ('generated_at', models.DateTimeField()),
                ('pdf_file', models.FileField(upload_to='reports/pdfs/')),
                ('pdf_sha256', models.CharField(max_length=64)),
                ('scanner_signature', models.CharField(default='ComplyLaw AI Scanner', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='scanner.scanresult')),
            ],
        ),
    ]
