# Generated by Django 5.1.1 on 2025-11-05 18:46

import django.db.models.deletion
import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scanner', '0003_scanresult__breach_alerts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('pdf_path', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('_findings', encrypted_model_fields.fields.EncryptedTextField(default='[]')),
                ('scan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='scanner.scanresult')),
            ],
        ),
    ]
