# Generated by Django 5.1.1 on 2025-11-06 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        ('scanner', '0004_alter_scanresult_options_scanresult_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliancereport',
            name='scan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_report', to='scanner.scanresult'),
        ),
    ]
