# Generated by Django 5.1.1 on 2025-11-07 19:19

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_compliancereport_scan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compliancereport',
            options={'ordering': ['-generated_at'], 'verbose_name': 'Compliance Report', 'verbose_name_plural': 'Compliance Reports'},
        ),
        migrations.RemoveField(
            model_name='compliancereport',
            name='pdf_path',
        ),
        migrations.AddField(
            model_name='compliancereport',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='reports/pdfs/'),
        ),
        migrations.AlterField(
            model_name='compliancereport',
            name='_findings',
            field=encrypted_model_fields.fields.EncryptedTextField(default='[]', help_text='Encrypted JSON list of findings'),
        ),
    ]
