# Generated by Django 5.1.1 on 2025-11-14 16:21

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_compliancereport_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliancereport',
            name='_findings',
            field=encrypted_model_fields.fields.EncryptedTextField(default='[]'),
        ),
    ]
