# Generated by Django 5.1.1 on 2025-12-14 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_compliancereport__findings'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifiedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(max_length=16, unique=True)),
                ('domain', models.CharField(max_length=255)),
                ('audit_date', models.DateField()),
                ('generated_at', models.DateTimeField()),
                ('compliance_grade', models.CharField(max_length=4)),
                ('risk_score', models.IntegerField()),
                ('issues_found', models.IntegerField()),
                ('frameworks', models.JSONField()),
                ('pdf_file', models.FileField(upload_to='reports/pdfs/')),
                ('pdf_sha256', models.CharField(max_length=64)),
                ('scanner_signature', models.CharField(default='ComplyLaw AI Scanner', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
