# Generated by Django 5.1.1 on 2025-12-14 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_verifiedreport'),
        ('scanner', '0012_alter_scanresult_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(max_length=16, unique=True)),
                ('domain', models.CharField(max_length=255)),
                ('generated_at', models.DateTimeField()),
                ('pdf_file', models.FileField(upload_to='reports/pdfs/')),
                ('pdf_sha256', models.CharField(max_length=64)),
                ('scanner_signature', models.CharField(default='ComplyLaw AI Scanner', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='scanner.scanresult')),
            ],
        ),
    ]
