# Generated by Django 5.1.1 on 2025-12-21 18:35

import django.db.models.deletion
import encrypted_model_fields.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255)),
                ('scan_date', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('current_step', models.CharField(blank=True, default='', max_length=200)),
                ('progress', models.IntegerField(default=0)),
                ('_raw_data', encrypted_model_fields.fields.EncryptedTextField(default='{}')),
                ('_breach_alerts', encrypted_model_fields.fields.EncryptedTextField(default='{}')),
                ('_checklist_status', encrypted_model_fields.fields.EncryptedTextField(default='{}')),
                ('risk_score', models.FloatField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, max_length=1, null=True)),
                ('recommendations', models.JSONField(default=list)),
                ('anomaly_score', models.FloatField(blank=True, null=True)),
                ('scan_log', encrypted_model_fields.fields.EncryptedTextField(blank=True)),
                ('pdf_report_path', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('RUNNING', 'RUNNING'), ('COMPLETED', 'COMPLETED'), ('FAILED', 'FAILED'), ('CANCELLED', 'CANCELLED')], default='PENDING', max_length=10)),
                ('scan_id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='users.firmprofile')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scan_date'],
                'indexes': [models.Index(fields=['firm', 'scan_date'], name='scanner_sca_firm_id_8bf4bd_idx'), models.Index(fields=['status'], name='scanner_sca_status_ee58a9_idx')],
            },
        ),
    ]
