# Generated by Django 5.1.1 on 2025-11-05 18:40

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_date', models.DateTimeField(auto_now_add=True)),
                ('_raw_data', encrypted_model_fields.fields.EncryptedTextField(default='{}')),
                ('risk_score', models.FloatField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, max_length=1, null=True)),
                ('pdf_report_path', models.CharField(blank=True, max_length=500, null=True)),
                ('scan_log', encrypted_model_fields.fields.EncryptedTextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=10)),
            ],
        ),
    ]
