# Generated by Django 5.1.1 on 2025-11-05 18:46

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_initial'),
        ('users', '0002_firmprofile_updated_at_useraccount_last_scan_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanresult',
            name='_breach_alerts',
            field=encrypted_model_fields.fields.EncryptedTextField(default='{}'),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='_checklist_status',
            field=encrypted_model_fields.fields.EncryptedTextField(default='{}'),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='anomaly_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='scanresult',
            index=models.Index(fields=['firm', 'scan_date'], name='scanner_sca_firm_id_8bf4bd_idx'),
        ),
        migrations.AddIndex(
            model_name='scanresult',
            index=models.Index(fields=['status'], name='scanner_sca_status_ee58a9_idx'),
        ),
    ]
