# Generated by Django 5.1.1 on 2025-11-06 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0003_scanresult__breach_alerts_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scanresult',
            options={'ordering': ['-scan_date']},
        ),
        migrations.AddField(
            model_name='scanresult',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
