# Generated by Django 5.1.1 on 2025-11-06 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0004_alter_scanresult_options_scanresult_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanresult',
            name='recommendations',
            field=models.JSONField(default=list),
        ),
    ]
