# Generated by Django 5.1.1 on 2025-11-07 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0005_scanresult_recommendations'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanresult',
            name='domain',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
