# Generated by Django 5.1.1 on 2025-11-07 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0006_scanresult_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanresult',
            name='scan_id',
            field=models.CharField(default=1, editable=False, max_length=8, unique=True),
            preserve_default=False,
        ),
    ]
