# Generated by Django 5.1.1 on 2025-11-07 19:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0007_scanresult_scan_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanresult',
            name='scan_id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True),
        ),
    ]
