# Generated by Django 5.1.1 on 2025-11-08 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0008_alter_scanresult_scan_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanresult',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='pending', max_length=10),
        ),
    ]
