# Generated by Django 5.1.1 on 2025-11-14 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0009_alter_scanresult_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanresult',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='current_step',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
