# Generated by Django 5.1.1 on 2025-11-14 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0010_scanresult_completed_at_scanresult_current_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanresult',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('RUNNING', 'RUNNING'), ('COMPLETED', 'COMPLETED'), ('FAILED', 'FAILED'), ('CANCELLED', 'CANCELLED')], default='pending', max_length=10),
        ),
    ]
