# Generated by Django 5.1.1 on 2025-12-20 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklistresponse',
            options={'ordering': ['template__code']},
        ),
        migrations.AlterField(
            model_name='checklistresponse',
            name='status',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('partial', 'Partial'), ('pending', 'Pending'), ('na', 'N/A')], default='pending', max_length=10),
        ),
    ]
