# Generated by Django 5.1.1 on 2025-12-27 07:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0001_initial'),
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistsubmission',
            name='standard',
            field=models.CharField(db_index=True, default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checklistsubmission',
            name='scan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_audits', to='scanner.scanresult'),
        ),
        migrations.AlterUniqueTogether(
            name='checklistsubmission',
            unique_together={('scan', 'standard')},
        ),
    ]
